"""add action_executions table

Revision ID: 27a7bdf03233
Revises: 25181f4e201c
Create Date: 2026-08-22 05:48:13.624246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a7bdf03233'
down_revision: Union[str, Sequence[str], None] = '25181f4e201c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exception_case_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('resulting_reference', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exception_case_id'], ['exception_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_executions_exception_case_id'), 'action_executions', ['exception_case_id'], unique=False)
    op.create_index(op.f('ix_action_executions_idempotency_key'), 'action_executions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_executions_idempotency_key'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_exception_case_id'), table_name='action_executions')
    op.drop_table('action_executions')
    # ### end Alembic commands ###
