"""initial schema

Revision ID: 9bc6b67a00ed
Revises: 
Create Date: 2026-08-22 00:38:41.284725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc6b67a00ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_reference', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_dataset_id'), 'payments', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_dataset_id'), 'reconciliation_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_status'), 'reconciliation_runs', ['status'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('settlement_id', sa.String(), nullable=False),
    sa.Column('transaction_reference', sa.String(), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settlement_status', sa.String(length=20), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_dataset_id'), 'settlements', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_settlements_settlement_id'), 'settlements', ['settlement_id'], unique=True)
    op.create_index(op.f('ix_settlements_transaction_reference'), 'settlements', ['transaction_reference'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=False),
    sa.Column('settlement_reference', sa.String(), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('match_strategy', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('amount_difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_match_status'), 'reconciliation_results', ['match_status'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_payment_reference'), 'reconciliation_results', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_run_id'), 'reconciliation_results', ['run_id'], unique=False)
    op.create_table('exception_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('reconciliation_result_id', sa.String(), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=False),
    sa.Column('exception_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('financial_impact', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recommended_action', sa.String(length=20), nullable=False),
    sa.Column('auto_resolvable', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_result_id'], ['reconciliation_results.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_cases_exception_type'), 'exception_cases', ['exception_type'], unique=False)
    op.create_index(op.f('ix_exception_cases_payment_reference'), 'exception_cases', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_exception_cases_reconciliation_result_id'), 'exception_cases', ['reconciliation_result_id'], unique=False)
    op.create_index(op.f('ix_exception_cases_review_status'), 'exception_cases', ['review_status'], unique=False)
    op.create_index(op.f('ix_exception_cases_run_id'), 'exception_cases', ['run_id'], unique=False)
    op.create_index(op.f('ix_exception_cases_severity'), 'exception_cases', ['severity'], unique=False)
    op.create_table('auto_resolution_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exception_case_id', sa.String(), nullable=False),
    sa.Column('resolution_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('financial_impact', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_case_id'], ['exception_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_resolution_records_exception_case_id'), 'auto_resolution_records', ['exception_case_id'], unique=False)
    op.create_table('review_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exception_case_id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_case_id'], ['exception_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_audits_exception_case_id'), 'review_audits', ['exception_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_audits_exception_case_id'), table_name='review_audits')
    op.drop_table('review_audits')
    op.drop_index(op.f('ix_auto_resolution_records_exception_case_id'), table_name='auto_resolution_records')
    op.drop_table('auto_resolution_records')
    op.drop_index(op.f('ix_exception_cases_severity'), table_name='exception_cases')
    op.drop_index(op.f('ix_exception_cases_run_id'), table_name='exception_cases')
    op.drop_index(op.f('ix_exception_cases_review_status'), table_name='exception_cases')
    op.drop_index(op.f('ix_exception_cases_reconciliation_result_id'), table_name='exception_cases')
    op.drop_index(op.f('ix_exception_cases_payment_reference'), table_name='exception_cases')
    op.drop_index(op.f('ix_exception_cases_exception_type'), table_name='exception_cases')
    op.drop_table('exception_cases')
    op.drop_index(op.f('ix_reconciliation_results_run_id'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_payment_reference'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_match_status'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_settlements_transaction_reference'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settlement_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_dataset_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_reconciliation_runs_status'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_dataset_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_dataset_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
